---

- name: install some small, awesome packages to boost your life
  dnf: name={{item}} state=present
  with_items:
    - autoconf
    - aptitude
    - cloc
    - curl
    - htop
    - make
    - pinfo
    - proxychains
    - ranger
    - rlwrap
    - silversearcher-ag
    - texinfo
    - tig
    - tmux
    - vim
    - editorconfig
