---
- name: clone bossjones-dotfile
  git: repo=https://github.com/bossjones/bossjones-dotfiles.git
       dest="{{virtualenv_vars.DEV_DIR}}/bossjones-dotfiles"
       update=no
       depth=1
  become: "{{base_vars.USER}}"
  become_user: "{{base_vars.USER}}"


- name: clone jessfraz-dotfiles
  git: repo=https://github.com/jessfraz/dotfiles.git
       dest="{{virtualenv_vars.DEV_DIR}}/jessfraz-dotfiles"
       update=no
       depth=1
  become: "{{base_vars.USER}}"
  become_user: "{{base_vars.USER}}"

- name: clone jessfraz-dockerfiles
  git: repo=https://github.com/jessfraz/dockerfiles.git
       dest="{{virtualenv_vars.DEV_DIR}}/jessfraz-dockerfiles"
       update=yes
       depth=1
  become: "{{base_vars.USER}}"
  become_user: "{{base_vars.USER}}"
  changed_when: false
  ignore_errors: yes
  failed_when: false
  check_mode: no
