---

- include: dnf.yml
  when: ansible_pkg_mgr == 'dnf'

# - include: base.yml
#   sudo: no

- include: kern.yml

- name: install python3 stuff
  include: python.yml

- name: install shell stuff
  include: shell.yml

- set_fact:
    role_basic_done: true
