# setup_python.yml
---

- name: Install virtualenv and virtualenvwrapper
  become: yes
  become_method: sudo
  pip: name={{ item }}
       executable=pip3
       state=present
  with_items:
  - virtualenv
  - virtualenvwrapper
  - ipython

# pip3 install virtualenv virtualenvwrapper ipython

# - name: install ipython
#   pip: name=ipython
#        state=present
#        executable=pip3

- name: install numpy
  pip: name=numpy
       state=present
       executable=pip3

- name: configure pythonrc
  template: src="home/{{base_vars.USER}}/pythonrc.j2"
            dest="/home/{{base_vars.USER}}/.pythonrc"
            owner="{{base_vars.USER}}"
            group="{{base_vars.USER}}"
            mode=0644
            backup=yes
  tags:
  - pythonrc
  - configuration
