---
- name: Create ~user/dev and ~user/dev folders
  file: path="{{virtualenv_vars.DEV_DIR}}"
        state=directory
        mode=0755
        recurse=yes
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"

- name: Create ~user/.bin folders
  file: path="/home/{{base_vars.USER}}/.bin"
        state=directory
        mode=0755
        recurse=yes
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"

- name: clone bash_it
  git: repo=https://github.com/Bash-it/bash-it.git
       dest="/home/{{base_vars.USER}}/.bash_it"
       update=no
       depth=1
  become: "{{base_vars.USER}}"
  become_user: "{{base_vars.USER}}"

# Leaving this here because we need the folder structure in place to setup pocketsphinx
- name: Create ~user/.bash_it/themes/devops
  file: path="/home/{{base_vars.USER}}/.bash_it/themes/devops"
        state=directory
        mode=0755
        recurse=yes
        owner="{{base_vars.USER}}"
        group="{{base_vars.USER}}"

- name: configure devops.theme.bash
  template: src="home/{{base_vars.USER}}/bash_it/themes/devops/devops.theme.bash.j2"
            dest="/home/{{base_vars.USER}}/.bash_it/themes/devops/devops.theme.bash"
            owner="{{base_vars.USER}}"
            group="{{base_vars.USER}}"
            mode=0644
            backup=yes
  tags:
  - bash_it
  - configuration

- name: configure bash_profile
  template: src="home/{{base_vars.USER}}/bash_profile.j2"
            dest="/home/{{base_vars.USER}}/.bash_profile"
            owner="{{base_vars.USER}}"
            group="{{base_vars.USER}}"
            mode=0644
            backup=yes
  tags:
  - bash_profile
  - configuration

- name: configure bashrc
  template: src="home/{{base_vars.USER}}/bashrc.j2"
            dest="/home/{{base_vars.USER}}/.bashrc"
            owner="{{base_vars.USER}}"
            group="{{base_vars.USER}}"
            mode=0644
            backup=yes
  tags:
  - bashrc
  - configuration

- name: configure .super_aliases
  template: src="home/{{base_vars.USER}}/super_aliases.j2"
            dest="/home/{{base_vars.USER}}/.super_aliases"
            owner="{{base_vars.USER}}"
            group="{{base_vars.USER}}"
            mode=0644
            backup=yes
  tags:
  - super_aliases
  - configuration
