---
- name: install cli tools
  dnf: name={{item}} state=present
  with_items:
    - iftop
    - bmon
    - nmon
    - ncdu
    - iotop
    - dos2unix
    - traceroute
    - nethogs
    - sysstat
    - ncftp
    - gawk
    - iperf
    - ifstat
    - iptraf
    - dstat
    - sysstat
    - mtr
    - caca-utils
    - ImageMagick
    - gcc
    - lynx
    - ccze
    - whois
    - socat
    - tig
    - strace
    - tcpdump
    - autoconf
    - gcc
    - bison
    - flex
    - gcc-c++
    - gettext
    - kernel-devel
    - make
    - m4
    - ncurses-devel

# vim
# vim-common
# vim-doc
# curl
# net-tools
# nmap
# wget
# whois
# socat
# openssh-client
# openssh-server
# openssl
# libwww-perl
# tig
# git
# git-man
# subversion
# cvs
# apt-file
# alien
# iotop
# strace
# tcpdump
# iproute
# ltrace
# lsof
# inotify-tools
# sysstat
# ddd
# tshark
# mlocate
# tcl
# erlang
# python-pip
# python-dev
# tmux
# xmlstarlet
# xclip
# jq
# telnet
# athena-jot
# xterm
# eatmydata
# util-linux
# moreutils
# sshfs
# tree
# screen
# xdotool
# xmlto
# expect
# expect-dev
# coreutils
# build-essential
# zip
# unzip
# haproxy
# ansible
# nethogs
# iftop
# ranger
# mitmproxy
# ant
# ascii
# asciinema
# asciidoc
# golang
# rsync
# docker
# at
# cron
# expect-dev
# patch
# perl
# perl-base
# perl-doc
# perl-modules
# sed
# anacron
# mssh
# daemon
# fslint
# gocr
# netpipe-tcp
# netsed
# netsniff-ng
# pkg-config
# procps
# sudo
# tcpd
# time
# tree
# tofrodos
# sec
# rhino
# postgresql-client
# maven
# lsb-base
# lsb-release
# readline-common
# rlwrap
# software-properties-common
# ncurses-base
# ncurses-bin
# tcpflow
# graphviz
# linux-doc
# libcorelinux-doc

- name: check ruby versions installed for select users
  shell: |
    bash -lc "chown {{base_vars.USER}}:{{base_vars.USER}} -R /usr/lib/python3.5/site-packages/cheat/cheatsheets"
  become: yes
  become_method: sudo
  args:
    executable: /bin/bash

- name: cheatsheets hyenacommands
  copy: src=hyenacommands dest=/usr/lib/python3.5/site-packages/cheat/cheatsheets/hyenacommands
  become: yes
  become_user: "{{base_vars.USER}}"
  ignore_errors: yes


# vim vim-common vim-doc curl net-tools nmap wget whois socat openssh-client openssh-server openssl libwww-perl tig git git-man subversion cvs apt-file alien iotop strace tcpdump iproute ltrace lsof inotify-tools sysstat ddd tshark mlocate tcl erlang python-pip python-dev tmux xmlstarlet xclip jq telnet athena-jot xterm eatmydata util-linux moreutils sshfs tree screen xdotool xmlto expect expect-dev coreutils build-essential zip unzip haproxy ansible nethogs iftop ranger mitmproxy ant ascii asciinema asciidoc golang rsync docker at cron expect-dev patch perl perl-base perl-doc perl-modules
# sed anacron mssh daemon fslint gocr netpipe-tcp netsed netsniff-ng pkg-config procps sudo tcpd time tree tofrodos sec rhino postgresql-client maven lsb-base lsb-release readline-common rlwrap software-properties-common ncurses-base ncurses-bin tcpflow graphviz linux-doc libcorelinux-doc user-mode-linux-doc perl-doc vim-doc bup libmagick++-dev silversearcher-ag ruby-dev webfs etherape python2.7-examples sniffit tcpick tcpreplay tcpreen tcpspy tcputils darkstat stone fatrace bashdb gitg git-repair i7z sqlmap ndiff hollywood actiona dateutils youtube-dl dwdiff iodine tsocks mininet dnstracer squashfs-tools x11-utils
