---
- name: install cli tools
  dnf: name={{item}} state=present
  with_items:
    - iftop
    - bmon
    - nmon
    - ncdu
    - iotop
    - dos2unix
    - traceroute
    - nethogs
    - sysstat
    - ncftp
    - gawk
    - iperf
    - ifstat
    - iptraf
    - dstat
    - sysstat
    - mtr
    - caca-utils
    - ImageMagick
    - gcc
    - lynx
    - ccze
    - whois
    - socat
    - tig
    - strace
    - tcpdump
    - autoconf
    - gcc
    - bison
    - flex
    - gcc-c++
    - gettext
    - kernel-devel
    - make
    - m4
    - ncurses-devel
    - inotify-tools
    - xmlstarlet
    - xclip
    - jq
    - telnet
    - moreutils
    - expect
    - expect-devel
    - coreutils
    - ascii
    - asciinema
    - asciidoc
    - NetPIPE
    - netsed
    - sec
    - maven
    - ncurses-base
    - tcpflow
    - screenfetch
    - figlet
    - libcaca.x86_64
    - libcaca-devel
    - cpulimit
    - w3m
    - w3m-img

- name: check ruby versions installed for select users
  shell: |
    bash -lc "chown {{base_vars.USER}}:{{base_vars.USER}} -R /usr/lib/python3.5/site-packages/cheat/cheatsheets"
  become: yes
  become_method: sudo
  args:
    executable: /bin/bash

- name: cheatsheets hyena
  copy: src=hyena dest=/usr/lib/python3.5/site-packages/cheat/cheatsheets/hyena
  become: yes
  become_user: "{{base_vars.USER}}"
  ignore_errors: yes
